### ISSUE TITLE
remove for loops

### ISSUE THREAD

**Issue by rezaahmadzadeh** [ashwinner19/RL-Single-agent-algo#1]
https://github.com/ashwinner19/RL-Single-agent-algo/blob/d4f4c9831c808f210b57a18e79aca2115dd3b1f5/Q_learnong.py#L29-L33

Instead of using less efficient for loops replace `np.zeros` with `np.ones`. Even if you want to have both options, each can be done with the numpy functions. No need to use two for loops.

**Comment by ashwinner19** [comment]
Done
