### ISSUE TITLE
inefficient function (several issues included)

### ISSUE THREAD

**Issue by rezaahmadzadeh** [ashwinner19/RL-Single-agent-algo#2]
https://github.com/ashwinner19/RL-Single-agent-algo/blob/d4f4c9831c808f210b57a18e79aca2115dd3b1f5/Q_learnong.py#L13-L22

1) pick a better function name: `action_selection` or `get_action`.
2) remove extra code such as `actiion=[]`.
3) Don't need to define extra variables: `if np.random.rand() < epsilon` would work as fine. 
4) replace `position` with `state`
5) for the `else` part: isn't `np.argmax(Q[state])` already the action. Why do you need to do a `player.action[b]`
6) get rid of extra variables `a` and `b`.

**Comment by ashwinner19** [comment]
np.argmax gives the index of the action to store the exact action as right,left,.. have selected the value from player actions, rest of the fixes done
