### ISSUE TITLE
remove extra variable

### ISSUE THREAD

**Issue by rezaahmadzadeh** [ashwinner19/RL-Single-agent-algo#3]
https://github.com/ashwinner19/RL-Single-agent-algo/blob/8276b16c7d6c416a8ddcdc2e26333e07c5206330/Q_learnong.py#L13-L18

use `return` in each statement and remove the `returnval` variable
line 15 should be:         `return player.actions[np.random.choice(len(player.actions))] `

line 17 should be         `return player.actions[np.argmax(Q[position])] `
remove     `return returnval`

**Comment by ashwinner19** [comment]
Done
