### ISSUE TITLE
remove commented code

### ISSUE THREAD

**Issue by rezaahmadzadeh** [ashwinner19/RL-Single-agent-algo#7]
https://github.com/ashwinner19/RL-Single-agent-algo/blob/49cee0782497d630f4da724ca01a45d6d4723933/Q_learnong.py#L37-L47

Remove these commented lines.
If you need to get map-specific initial states, you should make a function that does that outside of the implementation of the algorithm.

**Comment by ashwinner19** [comment]
Done
