### ISSUE TITLE
inconsistent variables

### ISSUE THREAD

**Issue by rezaahmadzadeh** [ashwinner19/RL-Single-agent-algo#9]
https://github.com/ashwinner19/RL-Single-agent-algo/blob/49cee0782497d630f4da724ca01a45d6d4723933/Q_learnong.py#L55-L62

Avoid the use of inconsistent variable names such as `pos`, `position`, and `xp`.
Those make the code less readable. 
Use something like: `current_position` and `next_position` and I highly recommend replacing `position` with `state`.

**Comment by ashwinner19** [comment]
done
